"""add user is_active and internship is_removed

Revision ID: 30ad81556226
Revises: 31831b3b2a6f
Create Date: 2026-07-21 22:18:29.304233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30ad81556226'
down_revision: Union[str, None] = '31831b3b2a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internships', sa.Column('is_removed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('internships', 'is_removed')
    # ### end Alembic commands ###
