"""add notification type, link, and read index

Revision ID: 31831b3b2a6f
Revises: 470e2788926a
Create Date: 2026-07-21 21:15:48.396598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '31831b3b2a6f'
down_revision: Union[str, None] = '470e2788926a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('link', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_column('notifications', 'link')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
