"""add cover_note, education, location

Revision ID: 470e2788926a
Revises: 184c59b69c15
Create Date: 2026-07-21 00:08:02.076769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '470e2788926a'
down_revision: Union[str, None] = '184c59b69c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cover_note', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('education', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'education')
    op.drop_column('applications', 'cover_note')
    # ### end Alembic commands ###
